/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppAccountsTripsRouteImport } from './routes/_authenticated/app.accounts..trips'
import { Route as AuthenticatedAppAccountsMembersRouteImport } from './routes/_authenticated/app.accounts..members'
import { Route as AuthenticatedAppAccountsCategoriesRouteImport } from './routes/_authenticated/app.accounts..categories'
import { Route as AuthenticatedAppAccountsRouteImport } from './routes/_authenticated/app.accounts.'
import { Route as AuthenticatedAppAccountsTripsNewRouteImport } from './routes/_authenticated/app.accounts..trips.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAccountsTripsRoute =
  AuthenticatedAppAccountsTripsRouteImport.update({
    id: '/accounts/trips',
    path: '/accounts/trips',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAccountsMembersRoute =
  AuthenticatedAppAccountsMembersRouteImport.update({
    id: '/accounts/members',
    path: '/accounts/members',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAccountsCategoriesRoute =
  AuthenticatedAppAccountsCategoriesRouteImport.update({
    id: '/accounts/categories',
    path: '/accounts/categories',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAccountsRoute =
  AuthenticatedAppAccountsRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAccountsTripsNewRoute =
  AuthenticatedAppAccountsTripsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppAccountsTripsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/accounts/': typeof AuthenticatedAppAccountsRoute
  '/app/accounts/categories': typeof AuthenticatedAppAccountsCategoriesRoute
  '/app/accounts/members': typeof AuthenticatedAppAccountsMembersRoute
  '/app/accounts/trips': typeof AuthenticatedAppAccountsTripsRouteWithChildren
  '/app/accounts/trips/new': typeof AuthenticatedAppAccountsTripsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/accounts': typeof AuthenticatedAppAccountsRoute
  '/app/accounts/categories': typeof AuthenticatedAppAccountsCategoriesRoute
  '/app/accounts/members': typeof AuthenticatedAppAccountsMembersRoute
  '/app/accounts/trips': typeof AuthenticatedAppAccountsTripsRouteWithChildren
  '/app/accounts/trips/new': typeof AuthenticatedAppAccountsTripsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/accounts/': typeof AuthenticatedAppAccountsRoute
  '/_authenticated/app/accounts/categories': typeof AuthenticatedAppAccountsCategoriesRoute
  '/_authenticated/app/accounts/members': typeof AuthenticatedAppAccountsMembersRoute
  '/_authenticated/app/accounts/trips': typeof AuthenticatedAppAccountsTripsRouteWithChildren
  '/_authenticated/app/accounts/trips/new': typeof AuthenticatedAppAccountsTripsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/accounts/'
    | '/app/accounts/categories'
    | '/app/accounts/members'
    | '/app/accounts/trips'
    | '/app/accounts/trips/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/accounts'
    | '/app/accounts/categories'
    | '/app/accounts/members'
    | '/app/accounts/trips'
    | '/app/accounts/trips/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/accounts/'
    | '/_authenticated/app/accounts/categories'
    | '/_authenticated/app/accounts/members'
    | '/_authenticated/app/accounts/trips'
    | '/_authenticated/app/accounts/trips/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/accounts/trips': {
      id: '/_authenticated/app/accounts/trips'
      path: '/accounts/trips'
      fullPath: '/app/accounts/trips'
      preLoaderRoute: typeof AuthenticatedAppAccountsTripsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/accounts/members': {
      id: '/_authenticated/app/accounts/members'
      path: '/accounts/members'
      fullPath: '/app/accounts/members'
      preLoaderRoute: typeof AuthenticatedAppAccountsMembersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/accounts/categories': {
      id: '/_authenticated/app/accounts/categories'
      path: '/accounts/categories'
      fullPath: '/app/accounts/categories'
      preLoaderRoute: typeof AuthenticatedAppAccountsCategoriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/accounts/': {
      id: '/_authenticated/app/accounts/'
      path: '/accounts'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AuthenticatedAppAccountsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/accounts/trips/new': {
      id: '/_authenticated/app/accounts/trips/new'
      path: '/new'
      fullPath: '/app/accounts/trips/new'
      preLoaderRoute: typeof AuthenticatedAppAccountsTripsNewRouteImport
      parentRoute: typeof AuthenticatedAppAccountsTripsRoute
    }
  }
}

interface AuthenticatedAppAccountsTripsRouteChildren {
  AuthenticatedAppAccountsTripsNewRoute: typeof AuthenticatedAppAccountsTripsNewRoute
}

const AuthenticatedAppAccountsTripsRouteChildren: AuthenticatedAppAccountsTripsRouteChildren =
  {
    AuthenticatedAppAccountsTripsNewRoute:
      AuthenticatedAppAccountsTripsNewRoute,
  }

const AuthenticatedAppAccountsTripsRouteWithChildren =
  AuthenticatedAppAccountsTripsRoute._addFileChildren(
    AuthenticatedAppAccountsTripsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountsRoute: typeof AuthenticatedAppAccountsRoute
  AuthenticatedAppAccountsCategoriesRoute: typeof AuthenticatedAppAccountsCategoriesRoute
  AuthenticatedAppAccountsMembersRoute: typeof AuthenticatedAppAccountsMembersRoute
  AuthenticatedAppAccountsTripsRoute: typeof AuthenticatedAppAccountsTripsRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountsRoute: AuthenticatedAppAccountsRoute,
  AuthenticatedAppAccountsCategoriesRoute:
    AuthenticatedAppAccountsCategoriesRoute,
  AuthenticatedAppAccountsMembersRoute: AuthenticatedAppAccountsMembersRoute,
  AuthenticatedAppAccountsTripsRoute:
    AuthenticatedAppAccountsTripsRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
